sudo: false
cache: pip
language: python
python:
    - 3.6

install:
    - pip install pipenv
    - pipenv install --dev

script:
    - mkdocs build --verbose --clean --strict

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: site
 target-branch: master
 on:
   branch: docs
